FROM python:3.9-slim

RUN pip install --no-cache-dir torch==2.4.1 torchvision==0.19.1 lightning==2.4.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html

RUN pip --no-cache-dir install numpy==1.23.4 gdown==5.2.0 scikit-learn==1.5.2 timm==1.0.9 tensorboard==2.17.1 matplotlib==3.9.2

# set the working directory
WORKDIR /opt/mount/

# copy all files from current directory on host into container's working directory
COPY . .

# specify the command to run
CMD ["python", "src/infer.py"]
